package com.example.tiamedsadmin.service;

import com.example.tiamedsadmin.entity.TestProduct;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class TestService {

    public List<TestProduct> getDummyProducts() {
        return List.of(
                TestProduct.builder()
                        .therapeuticCategory("Vitamins & Nutraceuticals")
                        .therapeuticSubCategory("Multi Vitamins")
                        .productName("Sudocal-1000")
                        .molecule("Calcium Citrate, Vitamin D3, Magnesium Hydroxide, Zinc Sulphate")
                        .mechanismOfAction("Supplies calcium ions for bone mineralization, Increases intestinal calcium and phosphate absorption")
                        .primaryUse("Calcium deficiency, Osteoporosis, Vitamin D deficiency")
                        .dosageForm("Tablet")
                        .strengthNetQuantity("1000mg")
                        .warningsPrecautions("Keep out of reach of children. Do not exceed recommended dose.")
                        .productDescription("Multi-mineral supplement for bone health and immune support.")
                        .productImageUrl("https://example.com/images/sudocal-1000.jpg")
                        .productMarketingUrl("https://example.com/products/sudocal-1000")
                        .packagingUnit("Strip")
                        .numberOfUnits(15)
                        .packSize(10)
                        .minimumOrderQty(50)
                        .maxOrderQty(500)
                        .batchLotNumber("TT25-972B")
                        .manufacturingDate("2025-09-01")
                        .expiryDate("2027-08-01")
                        .storageCondition("Store in a cool, dry & dark place. Protect from light & moisture at temperature not exceeding 30°C.")
                        .stockQuantity(10000)
                        .dateOfEntry("2026-03-04")
                        .pricePerUnit(12.0)
                        .mrpInr(180.0)
                        .discountPercent(10.0)
                        .additionalDiscount(2.0)
                        .finalPrice(176.4)
                        .gstPercent(5.0)
                        .hsnCode("30049099")
                        .build(),

                TestProduct.builder()
                        .therapeuticCategory("Analgesics")
                        .therapeuticSubCategory("Pain Relief")
                        .productName("Paracetamol 500")
                        .molecule("Paracetamol")
                        .mechanismOfAction("Inhibits prostaglandin synthesis in the CNS, raises pain threshold")
                        .primaryUse("Fever, mild to moderate pain, headache")
                        .dosageForm("Tablet")
                        .strengthNetQuantity("500mg")
                        .warningsPrecautions("Avoid in hepatic impairment. Do not combine with other paracetamol products.")
                        .productDescription("Fast-acting paracetamol for pain and fever relief.")
                        .productImageUrl("https://example.com/images/paracetamol-500.jpg")
                        .productMarketingUrl("https://example.com/products/paracetamol-500")
                        .packagingUnit("Strip")
                        .numberOfUnits(10)
                        .packSize(10)
                        .minimumOrderQty(100)
                        .maxOrderQty(1000)
                        .batchLotNumber("PC26-101A")
                        .manufacturingDate("2025-11-01")
                        .expiryDate("2027-10-01")
                        .storageCondition("Store below 25°C. Keep away from moisture.")
                        .stockQuantity(50000)
                        .dateOfEntry("2026-01-10")
                        .pricePerUnit(2.5)
                        .mrpInr(25.0)
                        .discountPercent(5.0)
                        .additionalDiscount(0.0)
                        .finalPrice(23.75)
                        .gstPercent(12.0)
                        .hsnCode("30049011")
                        .build(),

                TestProduct.builder()
                        .therapeuticCategory("Antibiotics")
                        .therapeuticSubCategory("Broad Spectrum")
                        .productName("Amoxyclav 625")
                        .molecule("Amoxicillin, Clavulanate Potassium")
                        .mechanismOfAction("Inhibits bacterial cell wall synthesis; clavulanate inhibits beta-lactamase enzymes")
                        .primaryUse("Respiratory tract infections, urinary tract infections, skin infections")
                        .dosageForm("Tablet")
                        .strengthNetQuantity("625mg")
                        .warningsPrecautions("Caution in patients allergic to penicillin. Monitor renal function.")
                        .productDescription("Broad-spectrum antibiotic for bacterial infections.")
                        .productImageUrl("https://example.com/images/amoxyclav-625.jpg")
                        .productMarketingUrl("https://example.com/products/amoxyclav-625")
                        .packagingUnit("Strip")
                        .numberOfUnits(10)
                        .packSize(10)
                        .minimumOrderQty(50)
                        .maxOrderQty(500)
                        .batchLotNumber("AM26-203C")
                        .manufacturingDate("2025-12-01")
                        .expiryDate("2027-11-01")
                        .storageCondition("Store below 30°C. Protect from humidity.")
                        .stockQuantity(20000)
                        .dateOfEntry("2026-02-01")
                        .pricePerUnit(18.0)
                        .mrpInr(180.0)
                        .discountPercent(8.0)
                        .additionalDiscount(2.0)
                        .finalPrice(162.0)
                        .gstPercent(12.0)
                        .hsnCode("30041000")
                        .build(),

                TestProduct.builder()
                        .therapeuticCategory("Antidiabetics")
                        .therapeuticSubCategory("Biguanides")
                        .productName("Metformin 500 SR")
                        .molecule("Metformin Hydrochloride")
                        .mechanismOfAction("Decreases hepatic glucose production, improves insulin sensitivity")
                        .primaryUse("Type 2 diabetes mellitus")
                        .dosageForm("Sustained Release Tablet")
                        .strengthNetQuantity("500mg")
                        .warningsPrecautions("Contraindicated in renal impairment. Risk of lactic acidosis.")
                        .productDescription("Sustained-release metformin for blood glucose management in type 2 diabetes.")
                        .productImageUrl("https://example.com/images/metformin-500sr.jpg")
                        .productMarketingUrl("https://example.com/products/metformin-500sr")
                        .packagingUnit("Bottle")
                        .numberOfUnits(60)
                        .packSize(60)
                        .minimumOrderQty(30)
                        .maxOrderQty(300)
                        .batchLotNumber("MF26-315D")
                        .manufacturingDate("2025-10-01")
                        .expiryDate("2027-09-01")
                        .storageCondition("Store at room temperature. Keep away from direct sunlight.")
                        .stockQuantity(15000)
                        .dateOfEntry("2026-01-20")
                        .pricePerUnit(3.5)
                        .mrpInr(210.0)
                        .discountPercent(10.0)
                        .additionalDiscount(0.0)
                        .finalPrice(189.0)
                        .gstPercent(5.0)
                        .hsnCode("30049099")
                        .build(),

                TestProduct.builder()
                        .therapeuticCategory("Cardiovascular")
                        .therapeuticSubCategory("Antihypertensives")
                        .productName("Amlodipine 5mg")
                        .molecule("Amlodipine Besylate")
                        .mechanismOfAction("Blocks L-type calcium channels, causes vasodilation, reduces peripheral vascular resistance")
                        .primaryUse("Hypertension, stable angina, vasospastic angina")
                        .dosageForm("Tablet")
                        .strengthNetQuantity("5mg")
                        .warningsPrecautions("May cause peripheral oedema and flushing. Caution in hepatic impairment.")
                        .productDescription("Calcium channel blocker for hypertension and angina management.")
                        .productImageUrl("https://example.com/images/amlodipine-5mg.jpg")
                        .productMarketingUrl("https://example.com/products/amlodipine-5mg")
                        .packagingUnit("Strip")
                        .numberOfUnits(10)
                        .packSize(10)
                        .minimumOrderQty(50)
                        .maxOrderQty(500)
                        .batchLotNumber("AM26-418E")
                        .manufacturingDate("2025-08-01")
                        .expiryDate("2027-07-01")
                        .storageCondition("Store below 30°C. Protect from light.")
                        .stockQuantity(25000)
                        .dateOfEntry("2026-02-15")
                        .pricePerUnit(4.0)
                        .mrpInr(40.0)
                        .discountPercent(12.0)
                        .additionalDiscount(0.0)
                        .finalPrice(35.2)
                        .gstPercent(12.0)
                        .hsnCode("30049099")
                        .build(),

                TestProduct.builder()
                        .therapeuticCategory("Gastrointestinal")
                        .therapeuticSubCategory("Proton Pump Inhibitors")
                        .productName("Pantoprazole 40mg")
                        .molecule("Pantoprazole Sodium Sesquihydrate")
                        .mechanismOfAction("Irreversibly inhibits H+/K+ ATPase enzyme in gastric parietal cells")
                        .primaryUse("GERD, peptic ulcer disease, Zollinger-Ellison syndrome")
                        .dosageForm("Enteric Coated Tablet")
                        .strengthNetQuantity("40mg")
                        .warningsPrecautions("Long-term use may reduce magnesium levels. Risk of Clostridium difficile infection.")
                        .productDescription("Proton pump inhibitor for acid-related gastrointestinal disorders.")
                        .productImageUrl("https://example.com/images/pantoprazole-40mg.jpg")
                        .productMarketingUrl("https://example.com/products/pantoprazole-40mg")
                        .packagingUnit("Strip")
                        .numberOfUnits(14)
                        .packSize(14)
                        .minimumOrderQty(50)
                        .maxOrderQty(400)
                        .batchLotNumber("PT26-520F")
                        .manufacturingDate("2025-11-15")
                        .expiryDate("2027-10-15")
                        .storageCondition("Store below 25°C. Keep in original packaging.")
                        .stockQuantity(18000)
                        .dateOfEntry("2026-02-20")
                        .pricePerUnit(6.0)
                        .mrpInr(84.0)
                        .discountPercent(10.0)
                        .additionalDiscount(2.0)
                        .finalPrice(73.92)
                        .gstPercent(12.0)
                        .hsnCode("30049099")
                        .build(),

                TestProduct.builder()
                        .therapeuticCategory("Respiratory")
                        .therapeuticSubCategory("Bronchodilators")
                        .productName("Salbutamol 2.5mg Nebulizer")
                        .molecule("Salbutamol Sulphate")
                        .mechanismOfAction("Selective beta-2 adrenoceptor agonist causing bronchial smooth muscle relaxation")
                        .primaryUse("Bronchial asthma, COPD, bronchospasm")
                        .dosageForm("Nebulizer Solution")
                        .strengthNetQuantity("2.5mg/2.5ml")
                        .warningsPrecautions("Use with caution in hyperthyroidism and cardiovascular disease.")
                        .productDescription("Ready-to-use nebulizer solution for fast relief of bronchospasm.")
                        .productImageUrl("https://example.com/images/salbutamol-nebulizer.jpg")
                        .productMarketingUrl("https://example.com/products/salbutamol-nebulizer")
                        .packagingUnit("Vial")
                        .numberOfUnits(5)
                        .packSize(5)
                        .minimumOrderQty(20)
                        .maxOrderQty(200)
                        .batchLotNumber("SB26-622G")
                        .manufacturingDate("2025-10-01")
                        .expiryDate("2027-09-01")
                        .storageCondition("Store between 2-8°C. Do not freeze. Protect from light.")
                        .stockQuantity(8000)
                        .dateOfEntry("2026-03-01")
                        .pricePerUnit(15.0)
                        .mrpInr(75.0)
                        .discountPercent(8.0)
                        .additionalDiscount(0.0)
                        .finalPrice(69.0)
                        .gstPercent(12.0)
                        .hsnCode("30049099")
                        .build(),

                TestProduct.builder()
                        .therapeuticCategory("Dermatology")
                        .therapeuticSubCategory("Antifungals")
                        .productName("Clotrimazole 1% Cream")
                        .molecule("Clotrimazole")
                        .mechanismOfAction("Inhibits ergosterol synthesis disrupting fungal cell membrane integrity")
                        .primaryUse("Tinea pedis, tinea cruris, tinea corporis, cutaneous candidiasis")
                        .dosageForm("Cream")
                        .strengthNetQuantity("1% w/w / 20g")
                        .warningsPrecautions("For external use only. Avoid contact with eyes and mucous membranes.")
                        .productDescription("Topical antifungal cream for dermatological fungal infections.")
                        .productImageUrl("https://example.com/images/clotrimazole-cream.jpg")
                        .productMarketingUrl("https://example.com/products/clotrimazole-cream")
                        .packagingUnit("Tube")
                        .numberOfUnits(1)
                        .packSize(1)
                        .minimumOrderQty(30)
                        .maxOrderQty(300)
                        .batchLotNumber("CL26-724H")
                        .manufacturingDate("2025-07-01")
                        .expiryDate("2027-06-01")
                        .storageCondition("Store below 25°C. Do not refrigerate.")
                        .stockQuantity(12000)
                        .dateOfEntry("2026-01-15")
                        .pricePerUnit(55.0)
                        .mrpInr(55.0)
                        .discountPercent(5.0)
                        .additionalDiscount(0.0)
                        .finalPrice(52.25)
                        .gstPercent(12.0)
                        .hsnCode("30049099")
                        .build(),

                TestProduct.builder()
                        .therapeuticCategory("Ophthalmology")
                        .therapeuticSubCategory("Anti-Infectives")
                        .productName("Moxifloxacin Eye Drops")
                        .molecule("Moxifloxacin Hydrochloride")
                        .mechanismOfAction("Inhibits bacterial DNA gyrase and topoisomerase IV, preventing DNA replication")
                        .primaryUse("Bacterial conjunctivitis, corneal ulcers")
                        .dosageForm("Eye Drops")
                        .strengthNetQuantity("0.5% w/v / 5ml")
                        .warningsPrecautions("For ophthalmic use only. Discontinue if hypersensitivity occurs.")
                        .productDescription("Fluoroquinolone antibiotic eye drops for bacterial eye infections.")
                        .productImageUrl("https://example.com/images/moxifloxacin-eyedrops.jpg")
                        .productMarketingUrl("https://example.com/products/moxifloxacin-eyedrops")
                        .packagingUnit("Bottle")
                        .numberOfUnits(1)
                        .packSize(1)
                        .minimumOrderQty(20)
                        .maxOrderQty(200)
                        .batchLotNumber("MX26-826I")
                        .manufacturingDate("2025-06-01")
                        .expiryDate("2027-05-01")
                        .storageCondition("Store at room temperature (15-25°C). Discard 4 weeks after opening.")
                        .stockQuantity(5000)
                        .dateOfEntry("2026-02-10")
                        .pricePerUnit(120.0)
                        .mrpInr(120.0)
                        .discountPercent(10.0)
                        .additionalDiscount(0.0)
                        .finalPrice(108.0)
                        .gstPercent(12.0)
                        .hsnCode("30049099")
                        .build(),

                TestProduct.builder()
                        .therapeuticCategory("Hormones & Endocrinology")
                        .therapeuticSubCategory("Thyroid Agents")
                        .productName("Levothyroxine 50mcg")
                        .molecule("Levothyroxine Sodium")
                        .mechanismOfAction("Synthetic T4 hormone replacing or supplementing natural thyroid hormone")
                        .primaryUse("Hypothyroidism, goitre, thyroid cancer adjunct therapy")
                        .dosageForm("Tablet")
                        .strengthNetQuantity("50mcg")
                        .warningsPrecautions("Take on empty stomach. Monitor TSH regularly. Risk of cardiac arrhythmia in overdose.")
                        .productDescription("Synthetic thyroid hormone replacement for hypothyroidism management.")
                        .productImageUrl("https://example.com/images/levothyroxine-50mcg.jpg")
                        .productMarketingUrl("https://example.com/products/levothyroxine-50mcg")
                        .packagingUnit("Strip")
                        .numberOfUnits(30)
                        .packSize(30)
                        .minimumOrderQty(30)
                        .maxOrderQty(300)
                        .batchLotNumber("LT26-930J")
                        .manufacturingDate("2025-09-15")
                        .expiryDate("2027-08-15")
                        .storageCondition("Store below 25°C away from light and moisture. Do not refrigerate.")
                        .stockQuantity(22000)
                        .dateOfEntry("2026-03-10")
                        .pricePerUnit(4.5)
                        .mrpInr(135.0)
                        .discountPercent(7.0)
                        .additionalDiscount(1.0)
                        .finalPrice(123.48)
                        .gstPercent(5.0)
                        .hsnCode("30049099")
                        .build()
        );
    }
}