server:
  servlet:
    context-path: /api/v1

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY:dummy}
    secret-key: ${AWS_SECRET_KEY:dummy}
    region: ${AWS_REGION:ap-south-1}
    bucket-name: ${AWS_BUCKET_NAME:dummy}

spring:
  datasource:
    # Use DB_HOST to switch between local (default) and docker-compose.
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/admin_test_db?charSet=UTF8
    username: postgres
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:   # Email configuration
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:dummy}
    password: ${MAIL_PASSWORD:dummy}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  # Twilio sms
twilio:
  account-sid: ${ACCOUNT_SID:dummy}
  auth-token: ${AUTH_TOKEN:dummy}
  verify:
    service-sid: ${SERVICE_SID:dummy}

springdoc:
  swagger-ui:
    enabled: true
    try-it-out-enabled: true


logging:
  level:
    org.springframework.mail: DEBUG
    jakarta.mail: DEBUG